# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/neeraj/workspace/stosys/stosys-project-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/neeraj/workspace/stosys/stosys-project-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neeraj/workspace/stosys/stosys-project-master/CMakeFiles /home/neeraj/workspace/stosys/stosys-project-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neeraj/workspace/stosys/stosys-project-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named milestone2c

# Build rule for target.
milestone2c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 milestone2c
.PHONY : milestone2c

# fast build rule for target.
milestone2c/fast:
	$(MAKE) -f CMakeFiles/milestone2c.dir/build.make CMakeFiles/milestone2c.dir/build
.PHONY : milestone2c/fast

#=============================================================================
# Target rules for targets named milestone2

# Build rule for target.
milestone2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 milestone2
.PHONY : milestone2

# fast build rule for target.
milestone2/fast:
	$(MAKE) -f CMakeFiles/milestone2.dir/build.make CMakeFiles/milestone2.dir/build
.PHONY : milestone2/fast

#=============================================================================
# Target rules for targets named milestone3

# Build rule for target.
milestone3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 milestone3
.PHONY : milestone3

# fast build rule for target.
milestone3/fast:
	$(MAKE) -f CMakeFiles/milestone3.dir/build.make CMakeFiles/milestone3.dir/build
.PHONY : milestone3/fast

#=============================================================================
# Target rules for targets named milestone3c

# Build rule for target.
milestone3c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 milestone3c
.PHONY : milestone3c

# fast build rule for target.
milestone3c/fast:
	$(MAKE) -f CMakeFiles/milestone3c.dir/build.make CMakeFiles/milestone3c.dir/build
.PHONY : milestone3c/fast

#=============================================================================
# Target rules for targets named kv

# Build rule for target.
kv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kv
.PHONY : kv

# fast build rule for target.
kv/fast:
	$(MAKE) -f CMakeFiles/kv.dir/build.make CMakeFiles/kv.dir/build
.PHONY : kv/fast

src/assignment2_test_without_gc.o: src/assignment2_test_without_gc.cpp.o

.PHONY : src/assignment2_test_without_gc.o

# target to build an object file
src/assignment2_test_without_gc.cpp.o:
	$(MAKE) -f CMakeFiles/milestone2c.dir/build.make CMakeFiles/milestone2c.dir/src/assignment2_test_without_gc.cpp.o
	$(MAKE) -f CMakeFiles/milestone2.dir/build.make CMakeFiles/milestone2.dir/src/assignment2_test_without_gc.cpp.o
.PHONY : src/assignment2_test_without_gc.cpp.o

src/assignment2_test_without_gc.i: src/assignment2_test_without_gc.cpp.i

.PHONY : src/assignment2_test_without_gc.i

# target to preprocess a source file
src/assignment2_test_without_gc.cpp.i:
	$(MAKE) -f CMakeFiles/milestone2c.dir/build.make CMakeFiles/milestone2c.dir/src/assignment2_test_without_gc.cpp.i
	$(MAKE) -f CMakeFiles/milestone2.dir/build.make CMakeFiles/milestone2.dir/src/assignment2_test_without_gc.cpp.i
.PHONY : src/assignment2_test_without_gc.cpp.i

src/assignment2_test_without_gc.s: src/assignment2_test_without_gc.cpp.s

.PHONY : src/assignment2_test_without_gc.s

# target to generate assembly for a file
src/assignment2_test_without_gc.cpp.s:
	$(MAKE) -f CMakeFiles/milestone2c.dir/build.make CMakeFiles/milestone2c.dir/src/assignment2_test_without_gc.cpp.s
	$(MAKE) -f CMakeFiles/milestone2.dir/build.make CMakeFiles/milestone2.dir/src/assignment2_test_without_gc.cpp.s
.PHONY : src/assignment2_test_without_gc.cpp.s

src/assignment3_test_with_gc.o: src/assignment3_test_with_gc.cpp.o

.PHONY : src/assignment3_test_with_gc.o

# target to build an object file
src/assignment3_test_with_gc.cpp.o:
	$(MAKE) -f CMakeFiles/milestone3.dir/build.make CMakeFiles/milestone3.dir/src/assignment3_test_with_gc.cpp.o
	$(MAKE) -f CMakeFiles/milestone3c.dir/build.make CMakeFiles/milestone3c.dir/src/assignment3_test_with_gc.cpp.o
.PHONY : src/assignment3_test_with_gc.cpp.o

src/assignment3_test_with_gc.i: src/assignment3_test_with_gc.cpp.i

.PHONY : src/assignment3_test_with_gc.i

# target to preprocess a source file
src/assignment3_test_with_gc.cpp.i:
	$(MAKE) -f CMakeFiles/milestone3.dir/build.make CMakeFiles/milestone3.dir/src/assignment3_test_with_gc.cpp.i
	$(MAKE) -f CMakeFiles/milestone3c.dir/build.make CMakeFiles/milestone3c.dir/src/assignment3_test_with_gc.cpp.i
.PHONY : src/assignment3_test_with_gc.cpp.i

src/assignment3_test_with_gc.s: src/assignment3_test_with_gc.cpp.s

.PHONY : src/assignment3_test_with_gc.s

# target to generate assembly for a file
src/assignment3_test_with_gc.cpp.s:
	$(MAKE) -f CMakeFiles/milestone3.dir/build.make CMakeFiles/milestone3.dir/src/assignment3_test_with_gc.cpp.s
	$(MAKE) -f CMakeFiles/milestone3c.dir/build.make CMakeFiles/milestone3c.dir/src/assignment3_test_with_gc.cpp.s
.PHONY : src/assignment3_test_with_gc.cpp.s

src/cftl.o: src/cftl.c.o

.PHONY : src/cftl.o

# target to build an object file
src/cftl.c.o:
	$(MAKE) -f CMakeFiles/milestone2c.dir/build.make CMakeFiles/milestone2c.dir/src/cftl.c.o
	$(MAKE) -f CMakeFiles/milestone3c.dir/build.make CMakeFiles/milestone3c.dir/src/cftl.c.o
.PHONY : src/cftl.c.o

src/cftl.i: src/cftl.c.i

.PHONY : src/cftl.i

# target to preprocess a source file
src/cftl.c.i:
	$(MAKE) -f CMakeFiles/milestone2c.dir/build.make CMakeFiles/milestone2c.dir/src/cftl.c.i
	$(MAKE) -f CMakeFiles/milestone3c.dir/build.make CMakeFiles/milestone3c.dir/src/cftl.c.i
.PHONY : src/cftl.c.i

src/cftl.s: src/cftl.c.s

.PHONY : src/cftl.s

# target to generate assembly for a file
src/cftl.c.s:
	$(MAKE) -f CMakeFiles/milestone2c.dir/build.make CMakeFiles/milestone2c.dir/src/cftl.c.s
	$(MAKE) -f CMakeFiles/milestone3c.dir/build.make CMakeFiles/milestone3c.dir/src/cftl.c.s
.PHONY : src/cftl.c.s

src/ftl.o: src/ftl.cpp.o

.PHONY : src/ftl.o

# target to build an object file
src/ftl.cpp.o:
	$(MAKE) -f CMakeFiles/milestone2.dir/build.make CMakeFiles/milestone2.dir/src/ftl.cpp.o
	$(MAKE) -f CMakeFiles/milestone3.dir/build.make CMakeFiles/milestone3.dir/src/ftl.cpp.o
	$(MAKE) -f CMakeFiles/kv.dir/build.make CMakeFiles/kv.dir/src/ftl.cpp.o
.PHONY : src/ftl.cpp.o

src/ftl.i: src/ftl.cpp.i

.PHONY : src/ftl.i

# target to preprocess a source file
src/ftl.cpp.i:
	$(MAKE) -f CMakeFiles/milestone2.dir/build.make CMakeFiles/milestone2.dir/src/ftl.cpp.i
	$(MAKE) -f CMakeFiles/milestone3.dir/build.make CMakeFiles/milestone3.dir/src/ftl.cpp.i
	$(MAKE) -f CMakeFiles/kv.dir/build.make CMakeFiles/kv.dir/src/ftl.cpp.i
.PHONY : src/ftl.cpp.i

src/ftl.s: src/ftl.cpp.s

.PHONY : src/ftl.s

# target to generate assembly for a file
src/ftl.cpp.s:
	$(MAKE) -f CMakeFiles/milestone2.dir/build.make CMakeFiles/milestone2.dir/src/ftl.cpp.s
	$(MAKE) -f CMakeFiles/milestone3.dir/build.make CMakeFiles/milestone3.dir/src/ftl.cpp.s
	$(MAKE) -f CMakeFiles/kv.dir/build.make CMakeFiles/kv.dir/src/ftl.cpp.s
.PHONY : src/ftl.cpp.s

src/kv.o: src/kv.c.o

.PHONY : src/kv.o

# target to build an object file
src/kv.c.o:
	$(MAKE) -f CMakeFiles/kv.dir/build.make CMakeFiles/kv.dir/src/kv.c.o
.PHONY : src/kv.c.o

src/kv.i: src/kv.c.i

.PHONY : src/kv.i

# target to preprocess a source file
src/kv.c.i:
	$(MAKE) -f CMakeFiles/kv.dir/build.make CMakeFiles/kv.dir/src/kv.c.i
.PHONY : src/kv.c.i

src/kv.s: src/kv.c.s

.PHONY : src/kv.s

# target to generate assembly for a file
src/kv.c.s:
	$(MAKE) -f CMakeFiles/kv.dir/build.make CMakeFiles/kv.dir/src/kv.c.s
.PHONY : src/kv.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... milestone2c"
	@echo "... milestone2"
	@echo "... milestone3"
	@echo "... milestone3c"
	@echo "... kv"
	@echo "... edit_cache"
	@echo "... src/assignment2_test_without_gc.o"
	@echo "... src/assignment2_test_without_gc.i"
	@echo "... src/assignment2_test_without_gc.s"
	@echo "... src/assignment3_test_with_gc.o"
	@echo "... src/assignment3_test_with_gc.i"
	@echo "... src/assignment3_test_with_gc.s"
	@echo "... src/cftl.o"
	@echo "... src/cftl.i"
	@echo "... src/cftl.s"
	@echo "... src/ftl.o"
	@echo "... src/ftl.i"
	@echo "... src/ftl.s"
	@echo "... src/kv.o"
	@echo "... src/kv.i"
	@echo "... src/kv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

